// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Activate agreement
	ActivateAgreement(ctx context.Context, id int64) (RentalAgreement, error)
	// Add evidence to dispute
	AddDisputeEvidence(ctx context.Context, arg AddDisputeEvidenceParams) (DisputeCase, error)
	// Add response to rating
	AddResponseToRating(ctx context.Context, arg AddResponseToRatingParams) (UserRating, error)
	// Approve inspection agent
	ApproveInspectionAgent(ctx context.Context, arg ApproveInspectionAgentParams) (InspectionAgentProfile, error)
	// Approve inspection report
	ApproveInspectionReport(ctx context.Context, id int64) (InspectionReport, error)
	// Approve rental application
	ApproveRentalApplication(ctx context.Context, arg ApproveRentalApplicationParams) (RentalApplication, error)
	// Assign admin to dispute
	AssignAdminToDispute(ctx context.Context, arg AssignAdminToDisputeParams) (DisputeCase, error)
	// Assign inspection agent
	AssignInspectionAgent(ctx context.Context, arg AssignInspectionAgentParams) (InspectionRequest, error)
	// Cancel inspection
	CancelInspection(ctx context.Context, arg CancelInspectionParams) (InspectionRequest, error)
	// Cancel payment
	CancelPayment(ctx context.Context, id int64) (Payment, error)
	// Check if rating exists
	CheckRatingExists(ctx context.Context, arg CheckRatingExistsParams) (bool, error)
	// Check if search is cached
	CheckSearchCached(ctx context.Context, searchHash string) (bool, error)
	// Check if setting exists
	CheckSettingExists(ctx context.Context, settingKey string) (bool, error)
	// Check if tenant has application for property
	CheckTenantApplicationForProperty(ctx context.Context, arg CheckTenantApplicationForPropertyParams) (bool, error)
	// Clean up expired cache entries
	CleanupExpiredCache(ctx context.Context) error
	// Clean up expired sessions
	CleanupExpiredSessions(ctx context.Context) error
	// Clean up old audit logs
	CleanupOldAuditLogs(ctx context.Context, createdAt pgtype.Timestamptz) error
	// Clean up old cache entries
	CleanupOldCache(ctx context.Context, createdAt pgtype.Timestamptz) error
	// Clean up old conversations
	CleanupOldConversations(ctx context.Context, createdAt pgtype.Timestamptz) error
	// Clean up old sessions
	CleanupOldSessions(ctx context.Context, createdAt pgtype.Timestamptz) error
	// Close dispute
	CloseDispute(ctx context.Context, arg CloseDisputeParams) (DisputeCase, error)
	// Complete agreement
	CompleteAgreement(ctx context.Context, id int64) (RentalAgreement, error)
	// Complete inspection
	CompleteInspection(ctx context.Context, id int64) (InspectionRequest, error)
	// Confirm inspection
	ConfirmInspection(ctx context.Context, arg ConfirmInspectionParams) (InspectionRequest, error)
	// Count active cache entries
	CountActiveCacheEntries(ctx context.Context) (int64, error)
	// Count agent's inspection requests
	CountAgentInspectionRequests(ctx context.Context, inspectionAgentID pgtype.Int8) (int64, error)
	// Count approved reports by agent
	CountApprovedReportsByAgent(ctx context.Context, inspectionAgentID int64) (int64, error)
	// Count audit logs by action
	CountAuditLogsByAction(ctx context.Context, action AuditActionEnum) (int64, error)
	// Count audit logs by date range
	CountAuditLogsByDateRange(ctx context.Context, arg CountAuditLogsByDateRangeParams) (int64, error)
	// Count audit logs by entity
	CountAuditLogsByEntity(ctx context.Context, arg CountAuditLogsByEntityParams) (int64, error)
	// Count audit logs by user
	CountAuditLogsByUser(ctx context.Context, userID pgtype.Int8) (int64, error)
	// Count available properties
	CountAvailableProperties(ctx context.Context) (int64, error)
	// Count conversations by intent
	CountConversationsByIntent(ctx context.Context, intent pgtype.Text) (int64, error)
	// Count conversations by session
	CountConversationsBySession(ctx context.Context, sessionID string) (int64, error)
	// Count conversations by user
	CountConversationsByUser(ctx context.Context, userID int64) (int64, error)
	// Count disputes assigned to admin
	CountDisputesAssignedToAdmin(ctx context.Context, assignedAdminID pgtype.Int8) (int64, error)
	// Count disputes by status
	CountDisputesByStatus(ctx context.Context, status NullDisputeStatusEnum) (int64, error)
	// Count disputes for user (as complainant)
	CountDisputesForComplainant(ctx context.Context, complainantID int64) (int64, error)
	// Count disputes for user (as respondent)
	CountDisputesForRespondent(ctx context.Context, respondentID int64) (int64, error)
	// Count escalated conversations
	CountEscalatedConversations(ctx context.Context) (int64, error)
	// Count expired cache entries
	CountExpiredCacheEntries(ctx context.Context) (int64, error)
	// Count inspection requests by status
	CountInspectionRequestsByStatus(ctx context.Context, status NullInspectionStatusEnum) (int64, error)
	// Count inquiries for landlord
	CountLandlordInquiries(ctx context.Context, landlordID int64) (int64, error)
	// Count landlord's rental agreements
	CountLandlordRentalAgreements(ctx context.Context, landlordID int64) (int64, error)
	// Count landlord's rental applications
	CountLandlordRentalApplications(ctx context.Context, landlordID int64) (int64, error)
	// Count notifications by type for user
	CountNotificationsByType(ctx context.Context, arg CountNotificationsByTypeParams) (int64, error)
	// Count payments by status
	CountPaymentsByStatus(ctx context.Context, status NullPaymentStatusFullEnum) (int64, error)
	// Count pending approval reports
	CountPendingApprovalReports(ctx context.Context) (int64, error)
	// Count pending verifications
	CountPendingVerifications(ctx context.Context) (int64, error)
	// Count properties by landlord
	CountPropertiesByLandlord(ctx context.Context, landlordID int64) (int64, error)
	// Count inquiries for property
	CountPropertyInquiries(ctx context.Context, propertyID int64) (int64, error)
	// Count inquiries by type for property
	CountPropertyInquiriesByType(ctx context.Context, arg CountPropertyInquiriesByTypeParams) (int64, error)
	// Count media for property
	CountPropertyMedia(ctx context.Context, propertyID int64) (int64, error)
	// Count media by type for property
	CountPropertyMediaByType(ctx context.Context, arg CountPropertyMediaByTypeParams) (int64, error)
	// Count property rental applications
	CountPropertyRentalApplications(ctx context.Context, propertyID int64) (int64, error)
	// Count reviews for property
	CountPropertyReviews(ctx context.Context, propertyID int64) (int64, error)
	// Count saves for property
	CountPropertySaves(ctx context.Context, propertyID int64) (int64, error)
	// Count public settings
	CountPublicSettings(ctx context.Context) (int64, error)
	// Count ratings for user
	CountRatingsForUser(ctx context.Context, ratedUserID int64) (int64, error)
	// Count rental agreements by status
	CountRentalAgreementsByStatus(ctx context.Context, status NullAgreementStatusEnum) (int64, error)
	// Count rental applications by status
	CountRentalApplicationsByStatus(ctx context.Context, status NullApplicationStatusEnum) (int64, error)
	// Count reports by agent
	CountReportsByAgent(ctx context.Context, inspectionAgentID int64) (int64, error)
	// Count settings by type
	CountSettingsByType(ctx context.Context, settingType NullSettingTypeEnum) (int64, error)
	// Count system settings
	CountSystemSettings(ctx context.Context) (int64, error)
	// Count tenant's inspection requests
	CountTenantInspectionRequests(ctx context.Context, tenantID int64) (int64, error)
	// Count tenant's rental agreements
	CountTenantRentalAgreements(ctx context.Context, tenantID int64) (int64, error)
	// Count tenant's rental applications
	CountTenantRentalApplications(ctx context.Context, tenantID int64) (int64, error)
	// Count total cache entries
	CountTotalCacheEntries(ctx context.Context) (int64, error)
	// Count unread inquiries for landlord
	CountUnreadLandlordInquiries(ctx context.Context, landlordID int64) (int64, error)
	// Count unread messages for user
	CountUnreadMessages(ctx context.Context, recipientID int64) (int64, error)
	// Count unread messages from sender
	CountUnreadMessagesFromSender(ctx context.Context, arg CountUnreadMessagesFromSenderParams) (int64, error)
	// Count unread notifications for user
	CountUnreadNotifications(ctx context.Context, userID int64) (int64, error)
	// Count user active sessions
	CountUserActiveSessions(ctx context.Context, userID int64) (int64, error)
	// Count user earnings
	CountUserEarnings(ctx context.Context, payeeID pgtype.Int8) (int64, error)
	// Count total notifications for user
	CountUserNotifications(ctx context.Context, userID int64) (int64, error)
	// Count user payments
	CountUserPayments(ctx context.Context, payerID int64) (int64, error)
	// Count user's saved properties
	CountUserSavedProperties(ctx context.Context, tenantID int64) (int64, error)
	// Count user total sessions
	CountUserTotalSessions(ctx context.Context, userID int64) (int64, error)
	// Count users by type
	CountUsersByType(ctx context.Context, userType UserTypeEnum) (int64, error)
	// Count verified reviews for property
	CountVerifiedPropertyReviews(ctx context.Context, propertyID int64) (int64, error)
	// Count verified ratings for user
	CountVerifiedRatingsForUser(ctx context.Context, ratedUserID int64) (int64, error)
	// Create audit log
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// Create chatbot conversation
	CreateChatbotConversation(ctx context.Context, arg CreateChatbotConversationParams) (ChatbotConversation, error)
	// Create dispute case
	CreateDisputeCase(ctx context.Context, arg CreateDisputeCaseParams) (DisputeCase, error)
	// Create a new inspection agent profile
	CreateInspectionAgentProfile(ctx context.Context, arg CreateInspectionAgentProfileParams) (InspectionAgentProfile, error)
	// Create inspection report
	CreateInspectionReport(ctx context.Context, arg CreateInspectionReportParams) (InspectionReport, error)
	// Create inspection request
	CreateInspectionRequest(ctx context.Context, arg CreateInspectionRequestParams) (InspectionRequest, error)
	// Create a new landlord profile
	CreateLandlordProfile(ctx context.Context, arg CreateLandlordProfileParams) (LandlordProfile, error)
	// Create message
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// Create notification
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Create payment
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// Create a new property
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	// Create property community review
	CreatePropertyCommunityReview(ctx context.Context, arg CreatePropertyCommunityReviewParams) (PropertyCommunityReview, error)
	// Create property inquiry
	CreatePropertyInquiry(ctx context.Context, arg CreatePropertyInquiryParams) (PropertyInquiry, error)
	// Create property media
	CreatePropertyMedia(ctx context.Context, arg CreatePropertyMediaParams) (PropertyMedium, error)
	// Create property search cache
	CreatePropertySearchCache(ctx context.Context, arg CreatePropertySearchCacheParams) (PropertySearchCache, error)
	// Create rental agreement
	CreateRentalAgreement(ctx context.Context, arg CreateRentalAgreementParams) (RentalAgreement, error)
	// Create rental application
	CreateRentalApplication(ctx context.Context, arg CreateRentalApplicationParams) (RentalApplication, error)
	// Create system setting
	CreateSystemSetting(ctx context.Context, arg CreateSystemSettingParams) (SystemSetting, error)
	// Create a new tenant profile
	CreateTenantProfile(ctx context.Context, arg CreateTenantProfileParams) (TenantProfile, error)
	// Create a new user
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Create user rating
	CreateUserRating(ctx context.Context, arg CreateUserRatingParams) (UserRating, error)
	// Create user session
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	// Create a new user verification
	CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) (UserVerification, error)
	// Deactivate all user sessions except current
	DeactivateOtherUserSessions(ctx context.Context, arg DeactivateOtherUserSessionsParams) error
	// Deactivate session
	DeactivateSession(ctx context.Context, sessionToken string) error
	// Deactivate user sessions
	DeactivateUserSessions(ctx context.Context, userID int64) error
	// Decrement landlord property count
	DecrementLandlordPropertyCount(ctx context.Context, userID int64) error
	// Decrement helpful votes
	DecrementReviewHelpfulVotes(ctx context.Context, id int64) error
	// Delete all media for property
	DeleteAllPropertyMedia(ctx context.Context, propertyID int64) error
	// Delete all user notifications
	DeleteAllUserNotifications(ctx context.Context, userID int64) error
	// Delete all saved properties for user
	DeleteAllUserSavedProperties(ctx context.Context, tenantID int64) error
	// Delete all user sessions
	DeleteAllUserSessions(ctx context.Context, userID int64) error
	// Delete audit log
	DeleteAuditLog(ctx context.Context, id int64) error
	// Delete audit logs by user
	DeleteAuditLogsByUser(ctx context.Context, userID pgtype.Int8) error
	// Delete cache by search hash
	DeleteCacheBySearchHash(ctx context.Context, searchHash string) error
	// Delete conversation
	DeleteChatbotConversation(ctx context.Context, id int64) error
	// Delete conversation between users
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) error
	// Delete conversations by session
	DeleteConversationsBySession(ctx context.Context, sessionID string) error
	// Delete dispute case
	DeleteDisputeCase(ctx context.Context, id int64) error
	// Delete inspection agent profile
	DeleteInspectionAgentProfile(ctx context.Context, userID int64) error
	// Delete inspection report
	DeleteInspectionReport(ctx context.Context, id int64) error
	// Delete inspection request
	DeleteInspectionRequest(ctx context.Context, id int64) error
	// Delete landlord profile
	DeleteLandlordProfile(ctx context.Context, userID int64) error
	// Delete message
	DeleteMessage(ctx context.Context, id int64) error
	// Delete notification
	DeleteNotification(ctx context.Context, id int64) error
	// Delete old notifications
	DeleteOldNotifications(ctx context.Context, createdAt pgtype.Timestamptz) error
	// Delete payment
	DeletePayment(ctx context.Context, id int64) error
	// Delete property (soft delete)
	DeleteProperty(ctx context.Context, id int64) error
	// Delete property community review
	DeletePropertyCommunityReview(ctx context.Context, id int64) error
	// Delete property inquiry
	DeletePropertyInquiry(ctx context.Context, id int64) error
	// Delete property media
	DeletePropertyMedia(ctx context.Context, id int64) error
	// Delete property search cache
	DeletePropertySearchCache(ctx context.Context, id int64) error
	// Delete rental agreement
	DeleteRentalAgreement(ctx context.Context, id int64) error
	// Delete rental application
	DeleteRentalApplication(ctx context.Context, id int64) error
	// Delete saved property by ID
	DeleteSavedProperty(ctx context.Context, id int64) error
	// Delete system setting
	DeleteSystemSetting(ctx context.Context, settingKey string) error
	// Delete tenant profile
	DeleteTenantProfile(ctx context.Context, userID int64) error
	// Delete user (soft delete by setting inactive)
	DeleteUser(ctx context.Context, id int64) error
	// Delete user rating
	DeleteUserRating(ctx context.Context, id int64) error
	// Delete user session
	DeleteUserSession(ctx context.Context, id int64) error
	// Delete user verification
	DeleteUserVerification(ctx context.Context, id int64) error
	// Update conversation escalation
	EscalateConversation(ctx context.Context, arg EscalateConversationParams) (ChatbotConversation, error)
	// Extend cache expiry
	ExtendCacheExpiry(ctx context.Context, arg ExtendCacheExpiryParams) (PropertySearchCache, error)
	// Fail payment
	FailPayment(ctx context.Context, arg FailPaymentParams) (Payment, error)
	// Get active cache entries
	GetActiveCacheEntries(ctx context.Context, arg GetActiveCacheEntriesParams) ([]PropertySearchCache, error)
	// Get active agreements for landlord
	GetActiveLandlordAgreements(ctx context.Context, arg GetActiveLandlordAgreementsParams) ([]GetActiveLandlordAgreementsRow, error)
	// Get active agreements for tenant
	GetActiveTenantAgreements(ctx context.Context, arg GetActiveTenantAgreementsParams) ([]GetActiveTenantAgreementsRow, error)
	// Get admin dispute workload
	GetAdminDisputeWorkload(ctx context.Context, assignedAdminID pgtype.Int8) (GetAdminDisputeWorkloadRow, error)
	// Get agent's inspection requests
	GetAgentInspectionRequests(ctx context.Context, arg GetAgentInspectionRequestsParams) ([]GetAgentInspectionRequestsRow, error)
	// Get inspection statistics for agent
	GetAgentInspectionStats(ctx context.Context, inspectionAgentID pgtype.Int8) (GetAgentInspectionStatsRow, error)
	// Get agent ratings
	GetAgentRatings(ctx context.Context, arg GetAgentRatingsParams) ([]GetAgentRatingsRow, error)
	// Get agreement statistics
	GetAgreementStatistics(ctx context.Context) (GetAgreementStatisticsRow, error)
	// Get agreements pending signatures
	GetAgreementsPendingSignatures(ctx context.Context, arg GetAgreementsPendingSignaturesParams) ([]GetAgreementsPendingSignaturesRow, error)
	// Get all system settings
	GetAllSystemSettings(ctx context.Context, arg GetAllSystemSettingsParams) ([]SystemSetting, error)
	// Get application conversation
	GetApplicationConversation(ctx context.Context, arg GetApplicationConversationParams) ([]GetApplicationConversationRow, error)
	// Get approved reports by date range
	GetApprovedReportsByDateRange(ctx context.Context, arg GetApprovedReportsByDateRangeParams) ([]GetApprovedReportsByDateRangeRow, error)
	// Get audit log by ID
	GetAuditLogByID(ctx context.Context, id int64) (AuditLog, error)
	// Get audit log with user details
	GetAuditLogWithUserDetails(ctx context.Context, id int64) (GetAuditLogWithUserDetailsRow, error)
	// Get audit logs by action
	GetAuditLogsByAction(ctx context.Context, arg GetAuditLogsByActionParams) ([]GetAuditLogsByActionRow, error)
	// Get audit logs by date range
	GetAuditLogsByDateRange(ctx context.Context, arg GetAuditLogsByDateRangeParams) ([]GetAuditLogsByDateRangeRow, error)
	// Get audit logs by entity
	GetAuditLogsByEntity(ctx context.Context, arg GetAuditLogsByEntityParams) ([]GetAuditLogsByEntityRow, error)
	// Get audit logs by entity type
	GetAuditLogsByEntityType(ctx context.Context, arg GetAuditLogsByEntityTypeParams) ([]GetAuditLogsByEntityTypeRow, error)
	// Get audit logs by IP address
	GetAuditLogsByIPAddress(ctx context.Context, arg GetAuditLogsByIPAddressParams) ([]GetAuditLogsByIPAddressRow, error)
	// Get audit logs by user
	GetAuditLogsByUser(ctx context.Context, arg GetAuditLogsByUserParams) ([]AuditLog, error)
	// Get audit statistics
	GetAuditStatistics(ctx context.Context, createdAt pgtype.Timestamptz) (GetAuditStatisticsRow, error)
	// Get cache by search hash
	GetCacheBySearchHash(ctx context.Context, searchHash string) (PropertySearchCache, error)
	// Get cache entries by result count
	GetCacheEntriesByResultCount(ctx context.Context, arg GetCacheEntriesByResultCountParams) ([]PropertySearchCache, error)
	// Get cache hit statistics
	GetCacheHitStatistics(ctx context.Context, createdAt pgtype.Timestamptz) (GetCacheHitStatisticsRow, error)
	// Get cache statistics
	GetCacheStatistics(ctx context.Context) (GetCacheStatisticsRow, error)
	// Get chatbot conversation by ID
	GetChatbotConversationByID(ctx context.Context, id int64) (ChatbotConversation, error)
	// Get chatbot statistics
	GetChatbotStatistics(ctx context.Context, createdAt pgtype.Timestamptz) (GetChatbotStatisticsRow, error)
	// Get conversation between two users
	GetConversationBetweenUsers(ctx context.Context, arg GetConversationBetweenUsersParams) ([]GetConversationBetweenUsersRow, error)
	// Get conversations by agent
	GetConversationsByAgent(ctx context.Context, arg GetConversationsByAgentParams) ([]GetConversationsByAgentRow, error)
	// Get conversations by intent
	GetConversationsByIntent(ctx context.Context, arg GetConversationsByIntentParams) ([]GetConversationsByIntentRow, error)
	// Get conversations by session
	GetConversationsBySession(ctx context.Context, arg GetConversationsBySessionParams) ([]ChatbotConversation, error)
	// Get conversations by user
	GetConversationsByUser(ctx context.Context, arg GetConversationsByUserParams) ([]ChatbotConversation, error)
	// Get daily conversation counts
	GetDailyConversationCounts(ctx context.Context, arg GetDailyConversationCountsParams) ([]GetDailyConversationCountsRow, error)
	// Get dispute case by ID
	GetDisputeCaseByID(ctx context.Context, id int64) (DisputeCase, error)
	// Get dispute case with details
	GetDisputeCaseWithDetails(ctx context.Context, id int64) (GetDisputeCaseWithDetailsRow, error)
	// Get dispute statistics
	GetDisputeStatistics(ctx context.Context, createdAt pgtype.Timestamptz) (GetDisputeStatisticsRow, error)
	// Get disputes assigned to admin
	GetDisputesAssignedToAdmin(ctx context.Context, arg GetDisputesAssignedToAdminParams) ([]GetDisputesAssignedToAdminRow, error)
	// Get disputes by entity
	GetDisputesByEntity(ctx context.Context, arg GetDisputesByEntityParams) ([]GetDisputesByEntityRow, error)
	// Get disputes by status
	GetDisputesByStatus(ctx context.Context, arg GetDisputesByStatusParams) ([]GetDisputesByStatusRow, error)
	// Get disputes by type
	GetDisputesByType(ctx context.Context, arg GetDisputesByTypeParams) ([]GetDisputesByTypeRow, error)
	// Get disputes for complainant
	GetDisputesForComplainant(ctx context.Context, arg GetDisputesForComplainantParams) ([]GetDisputesForComplainantRow, error)
	// Get disputes for respondent
	GetDisputesForRespondent(ctx context.Context, arg GetDisputesForRespondentParams) ([]GetDisputesForRespondentRow, error)
	// Get escalated conversations
	GetEscalatedConversations(ctx context.Context, arg GetEscalatedConversationsParams) ([]GetEscalatedConversationsRow, error)
	// Get expired cache entries
	GetExpiredCacheEntries(ctx context.Context, arg GetExpiredCacheEntriesParams) ([]PropertySearchCache, error)
	// Get expired sessions
	GetExpiredSessions(ctx context.Context, arg GetExpiredSessionsParams) ([]UserSession, error)
	// Get expiring agreements
	GetExpiringAgreements(ctx context.Context, arg GetExpiringAgreementsParams) ([]GetExpiringAgreementsRow, error)
	// Get failed login attempts
	GetFailedLoginAttempts(ctx context.Context, arg GetFailedLoginAttemptsParams) ([]AuditLog, error)
	// Get inspection agent profile by ID
	GetInspectionAgentProfileByID(ctx context.Context, id int64) (InspectionAgentProfile, error)
	// Get inspection agent profile by user ID
	GetInspectionAgentProfileByUserID(ctx context.Context, userID int64) (InspectionAgentProfile, error)
	// Get inspection conversation
	GetInspectionConversation(ctx context.Context, arg GetInspectionConversationParams) ([]GetInspectionConversationRow, error)
	// Get inspection report by ID
	GetInspectionReportByID(ctx context.Context, id int64) (InspectionReport, error)
	// Get inspection report by request ID
	GetInspectionReportByRequestID(ctx context.Context, inspectionRequestID int64) (InspectionReport, error)
	// Get inspection report with details
	GetInspectionReportWithDetails(ctx context.Context, id int64) (GetInspectionReportWithDetailsRow, error)
	// Get inspection request by ID
	GetInspectionRequestByID(ctx context.Context, id int64) (InspectionRequest, error)
	// Get inspection request with details
	GetInspectionRequestWithDetails(ctx context.Context, id int64) (GetInspectionRequestWithDetailsRow, error)
	// Get inspections by date range
	GetInspectionsByDateRange(ctx context.Context, arg GetInspectionsByDateRangeParams) ([]GetInspectionsByDateRangeRow, error)
	// Get intent statistics
	GetIntentStatistics(ctx context.Context, arg GetIntentStatisticsParams) ([]GetIntentStatisticsRow, error)
	// Get application statistics for landlord
	GetLandlordApplicationStats(ctx context.Context, landlordID int64) (GetLandlordApplicationStatsRow, error)
	// Get inquiries for landlord
	GetLandlordInquiries(ctx context.Context, arg GetLandlordInquiriesParams) ([]GetLandlordInquiriesRow, error)
	// Get inquiry statistics for landlord
	GetLandlordInquiryStats(ctx context.Context, landlordID int64) (GetLandlordInquiryStatsRow, error)
	// Get landlord's inspection requests
	GetLandlordInspectionRequests(ctx context.Context, arg GetLandlordInspectionRequestsParams) ([]GetLandlordInspectionRequestsRow, error)
	// Get landlord profile by ID
	GetLandlordProfileByID(ctx context.Context, id int64) (LandlordProfile, error)
	// Get landlord profile by user ID
	GetLandlordProfileByUserID(ctx context.Context, userID int64) (LandlordProfile, error)
	// Get landlord ratings
	GetLandlordRatings(ctx context.Context, arg GetLandlordRatingsParams) ([]GetLandlordRatingsRow, error)
	// Get landlord's rental agreements
	GetLandlordRentalAgreements(ctx context.Context, arg GetLandlordRentalAgreementsParams) ([]GetLandlordRentalAgreementsRow, error)
	// Get landlord's rental applications
	GetLandlordRentalApplications(ctx context.Context, arg GetLandlordRentalApplicationsParams) ([]GetLandlordRentalApplicationsRow, error)
	// Get low confidence conversations
	GetLowConfidenceConversations(ctx context.Context, arg GetLowConfidenceConversationsParams) ([]GetLowConfidenceConversationsRow, error)
	// Get message by ID
	GetMessageByID(ctx context.Context, id int64) (Message, error)
	// Get message with sender details
	GetMessageWithSenderDetails(ctx context.Context, id int64) (GetMessageWithSenderDetailsRow, error)
	// Get messages by property
	GetMessagesByProperty(ctx context.Context, arg GetMessagesByPropertyParams) ([]GetMessagesByPropertyRow, error)
	// Get most cached searches
	GetMostCachedSearches(ctx context.Context, arg GetMostCachedSearchesParams) ([]GetMostCachedSearchesRow, error)
	// Get most saved properties
	GetMostSavedProperties(ctx context.Context, arg GetMostSavedPropertiesParams) ([]GetMostSavedPropertiesRow, error)
	// Get notification by ID
	GetNotificationByID(ctx context.Context, id int64) (Notification, error)
	// Get notifications by date range
	GetNotificationsByDateRange(ctx context.Context, arg GetNotificationsByDateRangeParams) ([]GetNotificationsByDateRangeRow, error)
	// Get notifications by entity
	GetNotificationsByEntity(ctx context.Context, arg GetNotificationsByEntityParams) ([]GetNotificationsByEntityRow, error)
	// Get notifications by type for user
	GetNotificationsByTypeForUser(ctx context.Context, arg GetNotificationsByTypeForUserParams) ([]Notification, error)
	// Get open disputes
	GetOpenDisputes(ctx context.Context, arg GetOpenDisputesParams) ([]GetOpenDisputesRow, error)
	// Get payment audit logs
	GetPaymentAuditLogs(ctx context.Context, arg GetPaymentAuditLogsParams) ([]GetPaymentAuditLogsRow, error)
	// Get payment by gateway reference
	GetPaymentByGatewayReference(ctx context.Context, gatewayReference pgtype.Text) (Payment, error)
	// Get payment by ID
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	// Get payment by reference
	GetPaymentByReference(ctx context.Context, paymentReference string) (Payment, error)
	// Get payment statistics
	GetPaymentStatistics(ctx context.Context) (GetPaymentStatisticsRow, error)
	// Get payment with details
	GetPaymentWithDetails(ctx context.Context, id int64) (GetPaymentWithDetailsRow, error)
	// Get payments by date range
	GetPaymentsByDateRange(ctx context.Context, arg GetPaymentsByDateRangeParams) ([]GetPaymentsByDateRangeRow, error)
	// Get payments by entity
	GetPaymentsByEntity(ctx context.Context, arg GetPaymentsByEntityParams) ([]GetPaymentsByEntityRow, error)
	// Get payments by status
	GetPaymentsByStatus(ctx context.Context, arg GetPaymentsByStatusParams) ([]GetPaymentsByStatusRow, error)
	// Get payments by type
	GetPaymentsByType(ctx context.Context, arg GetPaymentsByTypeParams) ([]GetPaymentsByTypeRow, error)
	// Get pending applications for landlord
	GetPendingApplicationsForLandlord(ctx context.Context, arg GetPendingApplicationsForLandlordParams) ([]GetPendingApplicationsForLandlordRow, error)
	// Get pending approval reports
	GetPendingApprovalReports(ctx context.Context, arg GetPendingApprovalReportsParams) ([]GetPendingApprovalReportsRow, error)
	// Get pending email notifications
	GetPendingEmailNotifications(ctx context.Context, arg GetPendingEmailNotificationsParams) ([]GetPendingEmailNotificationsRow, error)
	// Get pending inspections for agents
	GetPendingInspectionsForAgents(ctx context.Context, arg GetPendingInspectionsForAgentsParams) ([]GetPendingInspectionsForAgentsRow, error)
	// Get pending payments
	GetPendingPayments(ctx context.Context, arg GetPendingPaymentsParams) ([]GetPendingPaymentsRow, error)
	// Get pending push notifications
	GetPendingPushNotifications(ctx context.Context, arg GetPendingPushNotificationsParams) ([]Notification, error)
	// Get pending SMS notifications
	GetPendingSMSNotifications(ctx context.Context, arg GetPendingSMSNotificationsParams) ([]GetPendingSMSNotificationsRow, error)
	// Get popular search caches
	GetPopularSearchCaches(ctx context.Context, arg GetPopularSearchCachesParams) ([]GetPopularSearchCachesRow, error)
	// Get primary media for property
	GetPrimaryPropertyMedia(ctx context.Context, propertyID int64) (PropertyMedium, error)
	// Get average ratings for property
	GetPropertyAverageRatings(ctx context.Context, propertyID int64) (GetPropertyAverageRatingsRow, error)
	// Get property by ID
	GetPropertyByID(ctx context.Context, id int64) (Property, error)
	// Get property community review by ID
	GetPropertyCommunityReviewByID(ctx context.Context, id int64) (PropertyCommunityReview, error)
	// Get reviews for property
	GetPropertyCommunityReviews(ctx context.Context, arg GetPropertyCommunityReviewsParams) ([]GetPropertyCommunityReviewsRow, error)
	// Get property conversation
	GetPropertyConversation(ctx context.Context, arg GetPropertyConversationParams) ([]GetPropertyConversationRow, error)
	// Get inquiries for property
	GetPropertyInquiries(ctx context.Context, arg GetPropertyInquiriesParams) ([]GetPropertyInquiriesRow, error)
	// Get property inquiry by ID
	GetPropertyInquiryByID(ctx context.Context, id int64) (PropertyInquiry, error)
	// Get inquiry with details
	GetPropertyInquiryWithDetails(ctx context.Context, id int64) (GetPropertyInquiryWithDetailsRow, error)
	// Get property media by ID
	GetPropertyMediaByID(ctx context.Context, id int64) (PropertyMedium, error)
	// Get all media for property
	GetPropertyMediaByPropertyID(ctx context.Context, propertyID int64) ([]PropertyMedium, error)
	// Get media by type for property
	GetPropertyMediaByType(ctx context.Context, arg GetPropertyMediaByTypeParams) ([]PropertyMedium, error)
	// Get applications for property
	GetPropertyRentalApplications(ctx context.Context, arg GetPropertyRentalApplicationsParams) ([]GetPropertyRentalApplicationsRow, error)
	// Get property search cache by ID
	GetPropertySearchCacheByID(ctx context.Context, id int64) (PropertySearchCache, error)
	// Get property with landlord details
	GetPropertyWithLandlord(ctx context.Context, id int64) (GetPropertyWithLandlordRow, error)
	// Get public system settings
	GetPublicSystemSettings(ctx context.Context) ([]GetPublicSystemSettingsRow, error)
	// Get rating for entity
	GetRatingForEntity(ctx context.Context, arg GetRatingForEntityParams) (GetRatingForEntityRow, error)
	// Get ratings by type for user
	GetRatingsByTypeForUser(ctx context.Context, arg GetRatingsByTypeForUserParams) ([]GetRatingsByTypeForUserRow, error)
	// Get ratings by user
	GetRatingsByUser(ctx context.Context, arg GetRatingsByUserParams) ([]GetRatingsByUserRow, error)
	// Get ratings for user
	GetRatingsForUser(ctx context.Context, arg GetRatingsForUserParams) ([]GetRatingsForUserRow, error)
	// Get recent audit logs
	GetRecentAuditLogs(ctx context.Context, arg GetRecentAuditLogsParams) ([]GetRecentAuditLogsRow, error)
	// Get recent conversations
	GetRecentChatbotConversations(ctx context.Context, arg GetRecentChatbotConversationsParams) ([]GetRecentChatbotConversationsRow, error)
	// Get recent messages for user
	GetRecentMessages(ctx context.Context, arg GetRecentMessagesParams) ([]GetRecentMessagesRow, error)
	// Get recent notifications across platform
	GetRecentNotifications(ctx context.Context, arg GetRecentNotificationsParams) ([]GetRecentNotificationsRow, error)
	// Get recent ratings
	GetRecentRatings(ctx context.Context, arg GetRecentRatingsParams) ([]GetRecentRatingsRow, error)
	// Get recently updated settings
	GetRecentlyUpdatedSettings(ctx context.Context, arg GetRecentlyUpdatedSettingsParams) ([]GetRecentlyUpdatedSettingsRow, error)
	// Get rental agreement by application ID
	GetRentalAgreementByApplicationID(ctx context.Context, applicationID int64) (RentalAgreement, error)
	// Get rental agreement by ID
	GetRentalAgreementByID(ctx context.Context, id int64) (RentalAgreement, error)
	// Get rental agreement with details
	GetRentalAgreementWithDetails(ctx context.Context, id int64) (GetRentalAgreementWithDetailsRow, error)
	// Get rental application by ID
	GetRentalApplicationByID(ctx context.Context, id int64) (RentalApplication, error)
	// Get rental application with details
	GetRentalApplicationWithDetails(ctx context.Context, id int64) (GetRentalApplicationWithDetailsRow, error)
	// Get report statistics
	GetReportStatistics(ctx context.Context) (GetReportStatisticsRow, error)
	// Get reports by agent
	GetReportsByAgent(ctx context.Context, arg GetReportsByAgentParams) ([]GetReportsByAgentRow, error)
	// Get saved property by ID
	GetSavedPropertyByID(ctx context.Context, id int64) (SavedProperty, error)
	// Get session statistics
	GetSessionStatistics(ctx context.Context) (GetSessionStatisticsRow, error)
	// Get session with user details
	GetSessionWithUserDetails(ctx context.Context, sessionToken string) (GetSessionWithUserDetailsRow, error)
	// Get sessions by IP address
	GetSessionsByIPAddress(ctx context.Context, arg GetSessionsByIPAddressParams) ([]GetSessionsByIPAddressRow, error)
	// Get setting statistics
	GetSettingStatistics(ctx context.Context) (GetSettingStatisticsRow, error)
	// Get settings by type
	GetSettingsByType(ctx context.Context, arg GetSettingsByTypeParams) ([]SystemSetting, error)
	// Get settings with updater info
	GetSettingsWithUpdaterInfo(ctx context.Context, arg GetSettingsWithUpdaterInfoParams) ([]GetSettingsWithUpdaterInfoRow, error)
	// Get system setting by ID
	GetSystemSettingByID(ctx context.Context, id int64) (SystemSetting, error)
	// Get system setting by key
	GetSystemSettingByKey(ctx context.Context, settingKey string) (SystemSetting, error)
	// Get inquiries for tenant
	GetTenantInquiries(ctx context.Context, arg GetTenantInquiriesParams) ([]GetTenantInquiriesRow, error)
	// Get tenant's inspection requests
	GetTenantInspectionRequests(ctx context.Context, arg GetTenantInspectionRequestsParams) ([]GetTenantInspectionRequestsRow, error)
	// Get tenant profile by ID
	GetTenantProfileByID(ctx context.Context, id int64) (TenantProfile, error)
	// Get tenant profile by user ID
	GetTenantProfileByUserID(ctx context.Context, userID int64) (TenantProfile, error)
	// Get tenant ratings
	GetTenantRatings(ctx context.Context, arg GetTenantRatingsParams) ([]GetTenantRatingsRow, error)
	// Get tenant's rental agreements
	GetTenantRentalAgreements(ctx context.Context, arg GetTenantRentalAgreementsParams) ([]GetTenantRentalAgreementsRow, error)
	// Get tenant's rental applications
	GetTenantRentalApplications(ctx context.Context, arg GetTenantRentalApplicationsParams) ([]GetTenantRentalApplicationsRow, error)
	// Get unassigned disputes
	GetUnassignedDisputes(ctx context.Context, arg GetUnassignedDisputesParams) ([]GetUnassignedDisputesRow, error)
	// Get unread inquiries for landlord
	GetUnreadLandlordInquiries(ctx context.Context, arg GetUnreadLandlordInquiriesParams) ([]GetUnreadLandlordInquiriesRow, error)
	// Get unread messages for user
	GetUnreadMessages(ctx context.Context, arg GetUnreadMessagesParams) ([]GetUnreadMessagesRow, error)
	// Get unread user notifications
	GetUnreadUserNotifications(ctx context.Context, arg GetUnreadUserNotificationsParams) ([]Notification, error)
	// Get user active sessions
	GetUserActiveSessions(ctx context.Context, arg GetUserActiveSessionsParams) ([]UserSession, error)
	// Get user activity summary
	GetUserActivitySummary(ctx context.Context, arg GetUserActivitySummaryParams) (GetUserActivitySummaryRow, error)
	// Get user by email
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Get user by ID
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Get user by phone
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	// Get user sessions
	GetUserChatbotSessions(ctx context.Context, arg GetUserChatbotSessionsParams) ([]GetUserChatbotSessionsRow, error)
	// Get user conversation summary
	GetUserConversationSummary(ctx context.Context, userID int64) (GetUserConversationSummaryRow, error)
	// Get user's conversations (distinct recipients)
	GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error)
	// Get user earning summary
	GetUserEarningSummary(ctx context.Context, payeeID pgtype.Int8) (GetUserEarningSummaryRow, error)
	// Get user earnings (as payee)
	GetUserEarnings(ctx context.Context, arg GetUserEarningsParams) ([]GetUserEarningsRow, error)
	// Get user login logs
	GetUserLoginLogs(ctx context.Context, arg GetUserLoginLogsParams) ([]GetUserLoginLogsRow, error)
	// Get notification statistics for user
	GetUserNotificationStats(ctx context.Context, userID int64) (GetUserNotificationStatsRow, error)
	// Get user notifications
	GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notification, error)
	// Get user payment summary
	GetUserPaymentSummary(ctx context.Context, payerID int64) (GetUserPaymentSummaryRow, error)
	// Get user payments (as payer)
	GetUserPayments(ctx context.Context, arg GetUserPaymentsParams) ([]GetUserPaymentsRow, error)
	// Get user's review for property
	GetUserPropertyReview(ctx context.Context, arg GetUserPropertyReviewParams) (PropertyCommunityReview, error)
	// Get user rating by ID
	GetUserRatingByID(ctx context.Context, id int64) (UserRating, error)
	// Get user rating statistics
	GetUserRatingStatistics(ctx context.Context, ratedUserID int64) (GetUserRatingStatisticsRow, error)
	// Get rating with details
	GetUserRatingWithDetails(ctx context.Context, id int64) (GetUserRatingWithDetailsRow, error)
	// Get user's saved properties
	GetUserSavedProperties(ctx context.Context, arg GetUserSavedPropertiesParams) ([]GetUserSavedPropertiesRow, error)
	// Get user's saved properties with landlord info
	GetUserSavedPropertiesWithLandlord(ctx context.Context, arg GetUserSavedPropertiesWithLandlordParams) ([]GetUserSavedPropertiesWithLandlordRow, error)
	// Get user session by ID
	GetUserSessionByID(ctx context.Context, id int64) (UserSession, error)
	// Get user session by token
	GetUserSessionByToken(ctx context.Context, sessionToken string) (UserSession, error)
	// Get user session summary
	GetUserSessionSummary(ctx context.Context, userID int64) (GetUserSessionSummaryRow, error)
	// Get user sessions
	GetUserSessions(ctx context.Context, arg GetUserSessionsParams) ([]UserSession, error)
	// Get user verification by ID
	GetUserVerificationByID(ctx context.Context, id int64) (UserVerification, error)
	// Get user verification by type
	GetUserVerificationByType(ctx context.Context, arg GetUserVerificationByTypeParams) (UserVerification, error)
	// Get user verifications by user ID
	GetUserVerificationsByUserID(ctx context.Context, userID int64) ([]UserVerification, error)
	// Get verification audit logs
	GetVerificationAuditLogs(ctx context.Context, arg GetVerificationAuditLogsParams) ([]GetVerificationAuditLogsRow, error)
	// Get verified reviews for property
	GetVerifiedPropertyCommunityReviews(ctx context.Context, arg GetVerifiedPropertyCommunityReviewsParams) ([]GetVerifiedPropertyCommunityReviewsRow, error)
	// Get verified ratings for user
	GetVerifiedRatingsForUser(ctx context.Context, arg GetVerifiedRatingsForUserParams) ([]GetVerifiedRatingsForUserRow, error)
	// Increment agent inspection count
	IncrementAgentInspectionCount(ctx context.Context, userID int64) error
	// Increment landlord property count
	IncrementLandlordPropertyCount(ctx context.Context, userID int64) error
	// Increment property views
	IncrementPropertyViews(ctx context.Context, id int64) error
	// Increment helpful votes
	IncrementReviewHelpfulVotes(ctx context.Context, id int64) error
	// Check if property is saved by user
	IsPropertySavedByUser(ctx context.Context, arg IsPropertySavedByUserParams) (bool, error)
	// Landlord sign agreement
	LandlordSignAgreement(ctx context.Context, id int64) (RentalAgreement, error)
	// List approved agents by area
	ListApprovedAgentsByArea(ctx context.Context, arg ListApprovedAgentsByAreaParams) ([]ListApprovedAgentsByAreaRow, error)
	// List featured properties
	ListFeaturedProperties(ctx context.Context, arg ListFeaturedPropertiesParams) ([]ListFeaturedPropertiesRow, error)
	// List landlords by property count
	ListLandlordsByPropertyCount(ctx context.Context, arg ListLandlordsByPropertyCountParams) ([]ListLandlordsByPropertyCountRow, error)
	// List pending agent applications
	ListPendingAgentApplications(ctx context.Context, arg ListPendingAgentApplicationsParams) ([]ListPendingAgentApplicationsRow, error)
	// List pending verifications
	ListPendingVerifications(ctx context.Context, arg ListPendingVerificationsParams) ([]ListPendingVerificationsRow, error)
	// List all properties with basic filtering
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error)
	// List properties by landlord
	ListPropertiesByLandlord(ctx context.Context, arg ListPropertiesByLandlordParams) ([]Property, error)
	// List properties by location
	ListPropertiesByLocation(ctx context.Context, arg ListPropertiesByLocationParams) ([]Property, error)
	// List recent properties
	ListRecentProperties(ctx context.Context, arg ListRecentPropertiesParams) ([]ListRecentPropertiesRow, error)
	// List recent reviews
	ListRecentPropertyReviews(ctx context.Context, arg ListRecentPropertyReviewsParams) ([]ListRecentPropertyReviewsRow, error)
	// List top agents by rating
	ListTopAgentsByRating(ctx context.Context, arg ListTopAgentsByRatingParams) ([]ListTopAgentsByRatingRow, error)
	// List top landlords by rating
	ListTopLandlordsByRating(ctx context.Context, arg ListTopLandlordsByRatingParams) ([]ListTopLandlordsByRatingRow, error)
	// List users by type
	ListUsersByType(ctx context.Context, arg ListUsersByTypeParams) ([]User, error)
	// List verifications by type and status
	ListVerificationsByTypeAndStatus(ctx context.Context, arg ListVerificationsByTypeAndStatusParams) ([]ListVerificationsByTypeAndStatusRow, error)
	// Mark all user notifications as read
	MarkAllUserNotificationsAsRead(ctx context.Context, userID int64) error
	// Mark inquiry as read
	MarkInquiryAsRead(ctx context.Context, id int64) error
	// Mark message as read
	MarkMessageAsRead(ctx context.Context, id int64) error
	// Mark multiple messages as read
	MarkMessagesAsRead(ctx context.Context, dollar_1 []int64) error
	// Mark notification as read
	MarkNotificationAsRead(ctx context.Context, id int64) error
	// Mark multiple notifications as read
	MarkNotificationsAsRead(ctx context.Context, dollar_1 []int64) error
	// Process payment
	ProcessPayment(ctx context.Context, arg ProcessPaymentParams) (Payment, error)
	// Refund payment
	RefundPayment(ctx context.Context, arg RefundPaymentParams) (Payment, error)
	// Reject inspection agent
	RejectInspectionAgent(ctx context.Context, userID int64) error
	// Reject inspection report
	RejectInspectionReport(ctx context.Context, id int64) error
	// Reject rental application
	RejectRentalApplication(ctx context.Context, arg RejectRentalApplicationParams) (RentalApplication, error)
	// Resolve dispute
	ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (DisputeCase, error)
	// Respond to inquiry
	RespondToInquiry(ctx context.Context, arg RespondToInquiryParams) (PropertyInquiry, error)
	// Save a property
	SaveProperty(ctx context.Context, arg SavePropertyParams) (SavedProperty, error)
	// Search cache entries
	SearchCacheEntries(ctx context.Context, arg SearchCacheEntriesParams) ([]PropertySearchCache, error)
	// Search conversations
	SearchChatbotConversations(ctx context.Context, arg SearchChatbotConversationsParams) ([]SearchChatbotConversationsRow, error)
	// Search messages
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	// Search properties with filters
	SearchProperties(ctx context.Context, arg SearchPropertiesParams) ([]SearchPropertiesRow, error)
	// Search settings
	SearchSettings(ctx context.Context, arg SearchSettingsParams) ([]SystemSetting, error)
	// Search tenant profiles by criteria
	SearchTenantProfiles(ctx context.Context, arg SearchTenantProfilesParams) ([]SearchTenantProfilesRow, error)
	// Search users
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	// Set primary media
	SetPrimaryMedia(ctx context.Context, arg SetPrimaryMediaParams) error
	// Tenant sign agreement
	TenantSignAgreement(ctx context.Context, id int64) (RentalAgreement, error)
	// Terminate agreement
	TerminateAgreement(ctx context.Context, id int64) (RentalAgreement, error)
	// Unsave a property
	UnsaveProperty(ctx context.Context, arg UnsavePropertyParams) error
	// Update agent banking details
	UpdateAgentBankingDetails(ctx context.Context, arg UpdateAgentBankingDetailsParams) (InspectionAgentProfile, error)
	// Update agent earnings
	UpdateAgentEarnings(ctx context.Context, arg UpdateAgentEarningsParams) error
	// Update agent service details
	UpdateAgentServiceDetails(ctx context.Context, arg UpdateAgentServiceDetailsParams) (InspectionAgentProfile, error)
	// Update agent stats
	UpdateAgentStats(ctx context.Context, arg UpdateAgentStatsParams) (InspectionAgentProfile, error)
	// Update agreement document
	UpdateAgreementDocument(ctx context.Context, arg UpdateAgreementDocumentParams) (RentalAgreement, error)
	// Update agreement status
	UpdateAgreementStatus(ctx context.Context, arg UpdateAgreementStatusParams) (RentalAgreement, error)
	// Update application documents
	UpdateApplicationDocuments(ctx context.Context, arg UpdateApplicationDocumentsParams) (RentalApplication, error)
	// Update employment details
	UpdateApplicationEmploymentDetails(ctx context.Context, arg UpdateApplicationEmploymentDetailsParams) (RentalApplication, error)
	// Update application references
	UpdateApplicationReferences(ctx context.Context, arg UpdateApplicationReferencesParams) (RentalApplication, error)
	// Update dispute case
	UpdateDisputeCase(ctx context.Context, arg UpdateDisputeCaseParams) (DisputeCase, error)
	// Update dispute status
	UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) (DisputeCase, error)
	// Update inquiry status
	UpdateInquiryStatus(ctx context.Context, arg UpdateInquiryStatusParams) (PropertyInquiry, error)
	// Update inspection agent profile
	UpdateInspectionAgentProfile(ctx context.Context, arg UpdateInspectionAgentProfileParams) (InspectionAgentProfile, error)
	// Update payment status
	UpdateInspectionPaymentStatus(ctx context.Context, arg UpdateInspectionPaymentStatusParams) (InspectionRequest, error)
	// Update inspection report
	UpdateInspectionReport(ctx context.Context, arg UpdateInspectionReportParams) (InspectionReport, error)
	// Update inspection request status
	UpdateInspectionRequestStatus(ctx context.Context, arg UpdateInspectionRequestStatusParams) (InspectionRequest, error)
	// Update landlord banking details
	UpdateLandlordBankingDetails(ctx context.Context, arg UpdateLandlordBankingDetailsParams) (LandlordProfile, error)
	// Update landlord business details
	UpdateLandlordBusinessDetails(ctx context.Context, arg UpdateLandlordBusinessDetailsParams) (LandlordProfile, error)
	// Update landlord guarantor details
	UpdateLandlordGuarantorDetails(ctx context.Context, arg UpdateLandlordGuarantorDetailsParams) (LandlordProfile, error)
	// Update landlord profile
	UpdateLandlordProfile(ctx context.Context, arg UpdateLandlordProfileParams) (LandlordProfile, error)
	// Update landlord stats
	UpdateLandlordStats(ctx context.Context, arg UpdateLandlordStatsParams) (LandlordProfile, error)
	// Update media caption
	UpdateMediaCaption(ctx context.Context, arg UpdateMediaCaptionParams) error
	// Update media display order
	UpdateMediaDisplayOrder(ctx context.Context, arg UpdateMediaDisplayOrderParams) error
	// Update notification
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (Notification, error)
	// Update email sent status
	UpdateNotificationEmailSent(ctx context.Context, id int64) error
	// Update push sent status
	UpdateNotificationPushSent(ctx context.Context, id int64) error
	// Update SMS sent status
	UpdateNotificationSMSSent(ctx context.Context, id int64) error
	// Update payment status
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	// Update property
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error)
	// Update property availability
	UpdatePropertyAvailability(ctx context.Context, arg UpdatePropertyAvailabilityParams) (Property, error)
	// Update property community review
	UpdatePropertyCommunityReview(ctx context.Context, arg UpdatePropertyCommunityReviewParams) (PropertyCommunityReview, error)
	// Update property media
	UpdatePropertyMedia(ctx context.Context, arg UpdatePropertyMediaParams) (PropertyMedium, error)
	// Update property status
	UpdatePropertyStatus(ctx context.Context, arg UpdatePropertyStatusParams) (Property, error)
	// Update rental agreement
	UpdateRentalAgreement(ctx context.Context, arg UpdateRentalAgreementParams) (RentalAgreement, error)
	// Update rental application status
	UpdateRentalApplicationStatus(ctx context.Context, arg UpdateRentalApplicationStatusParams) (RentalApplication, error)
	// Update report media
	UpdateReportMedia(ctx context.Context, arg UpdateReportMediaParams) (InspectionReport, error)
	// Update report summary
	UpdateReportSummary(ctx context.Context, arg UpdateReportSummaryParams) (InspectionReport, error)
	// Update search cache
	UpdateSearchCache(ctx context.Context, arg UpdateSearchCacheParams) (PropertySearchCache, error)
	// Update session activity
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
	// Update session location
	UpdateSessionLocation(ctx context.Context, arg UpdateSessionLocationParams) error
	// Update setting value
	UpdateSettingValue(ctx context.Context, arg UpdateSettingValueParams) (SystemSetting, error)
	// Update setting visibility
	UpdateSettingVisibility(ctx context.Context, arg UpdateSettingVisibilityParams) error
	// Update system setting
	UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) (SystemSetting, error)
	// Update tenant budget
	UpdateTenantBudget(ctx context.Context, arg UpdateTenantBudgetParams) (TenantProfile, error)
	// Update tenant employment details
	UpdateTenantEmploymentDetails(ctx context.Context, arg UpdateTenantEmploymentDetailsParams) (TenantProfile, error)
	// Update tenant preferences
	UpdateTenantPreferences(ctx context.Context, arg UpdateTenantPreferencesParams) (TenantProfile, error)
	// Update tenant profile
	UpdateTenantProfile(ctx context.Context, arg UpdateTenantProfileParams) (TenantProfile, error)
	// Update user
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Update user active status
	UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) error
	// Update user last login time
	UpdateUserLastLogin(ctx context.Context, id int64) error
	// Update user password
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Update user rating
	UpdateUserRating(ctx context.Context, arg UpdateUserRatingParams) (UserRating, error)
	// Update user verification status
	UpdateUserVerificationStatus(ctx context.Context, arg UpdateUserVerificationStatusParams) error
	// Update verification data
	UpdateVerificationData(ctx context.Context, arg UpdateVerificationDataParams) (UserVerification, error)
	// Update verification status
	UpdateVerificationStatus(ctx context.Context, arg UpdateVerificationStatusParams) (UserVerification, error)
	// Verify property
	VerifyProperty(ctx context.Context, arg VerifyPropertyParams) (Property, error)
	// Verify property review
	VerifyPropertyReview(ctx context.Context, id int64) error
	// Verify rating
	VerifyRating(ctx context.Context, id int64) error
	// Withdraw rental application
	WithdrawRentalApplication(ctx context.Context, id int64) (RentalApplication, error)
}

var _ Querier = (*Queries)(nil)
